# Site settings
title: terrehbyte | Terry Nguyen
email: terreh@terrehbyte.com
description: "If you're reading this, then it means that I'm actually putting work into getting the Jekyll variant of my website working!"
baseurl: ""
url: "http://github.terrehbyte.com"
webmaster_realname: Terry Nguyen
twitter_username: terrehbyte
github_username:  terrehbyte
paginate: 4

# Build settings
markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
    - with_toc_data

encoding: utf-8
timezone: US/Pacific
highlighter: pygments

permalink: /:year/:month/:day/:title/