# Site settings
title: terrehbyte
email: terreh@terrehbyte.com
description: "Jekyll Test; Please Ignore"
baseurl: ""
url: "http://github.terrehbyte.com"
twitter_username: terrehbyte
github_username:  terrehbyte

# Build settings
markdown: kramdown
permalink: pretty

# Markdown settings
kramdown:
    input: GFM

encoding: utf-8

timezone: US/Pacific

highlighter: pygments

permalink: /:year/:month/:day/:title/