# Site settings
title: terrehbyte
email: terreh@terrehbyte.com
description: "Programming and game development notes written by a developer working on games in Unity3D and Unreal Engine."
baseurl: ""
url: "https://terrehbyte.com"
webmaster_realname: Terry Nguyen
twitter_username: terrehbyte
github_username:  terrehbyte
paginate: 4

# Build settings
markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
    - with_toc_data
    - tables

encoding: utf-8
timezone: US/Pacific
highlighter: pygments

permalink: /:year/:month/:day/:title/

# Defaults
defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts