# Site settings
title: terrehbyte
email: terreh@terrehbyte.com
description: "Programming and game development notes written by a developer working on games in Unity3D and Unreal Engine."
baseurl: ""
url: "https://terrehbyte.com"
webmaster_realname: Terry Nguyen
twitter_username: terrehbyte
github_username:  terrehbyte

authors:
  terrehbyte:
    real_name: Terry Nguyen
    display_name: terrehbyte
    twitter: terrehbyte
    github: terrehbyte

# Build settings
safe: true

encoding: utf-8
timezone: US/Pacific

permalink: /:title/

exclude:
  - README.md
  - LICENSE.md
  - Gemfile
  - Gemfile.lock

whitelist:
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-coffeescript
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-sass-converter
  - jekyll-textile-converter


gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from

# Defaults
defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
#     redirect_from:
#         - {{ current.page.data }}
#        - /{{ page.date | date: "%Y/%m/%d" }}/
#        - /:year/:month/:day/:title/
